### ISSUE TITLE
[BUG] The Windows Settings menu doesn't disappear from the taskbar after being closed

### ISSUE THREAD

**Issue by Mortemtail** [eythaann/Seelen-UI#1270]
### Description of the issue

When I open the Windows Settings menu and try to close it, its icon doesn't disappear from Seelen UI's taskbar until I restart Seelen UI

### To reproduce

1. Open Seelen UI
2. Go to the Windows Settings menu
3. Close the Settings window
4. Observe the taskbar in Seelen UI
5. Notice that the Settings icon remains visible

### Expected behavior

When I close the Windows Settings window, its icon should be removed from Seelen UI’s taskbar, without needing to restart Seelen UI

### Evidence

- https://www.mediafire.com/file/5ram9to3osw772k/The_Bug_4.mp4/file
- [Seelen UI.log](https://github.com/user-attachments/files/23577576/Seelen.UI.log)
- [SLU Service.log](https://github.com/user-attachments/files/23577577/SLU.Service.log)

**Comment by Mortemtail** [comment]
I also noticed the same issues with the Task Manager, Computer Management, the media player, the screenshot tool, and the video player

**Comment by rainsun007** [comment]
windows lock screen will also appear on the taskbar and cannot be forcibly closed.

**Comment by eythaann** [comment]
this was fixed on v2.4.8

**Comment by Mortemtail** [comment]
Awesome, thanks a lot!

**Comment by Mortemtail** [comment]
> this was fixed on v2.4.8

So, everything works very well except for the Task Manager and the Computer Management app, their preview doesn’t work, and I can’t close them from the taskbar preview

**Comment by Mortemtail** [comment]
<img width="290" height="283" alt="Image" src="https://github.com/user-attachments/assets/8bb11b54-20f3-41a9-a15d-27253f49177c" />

<img width="321" height="299" alt="Image" src="https://github.com/user-attachments/assets/ef9272b0-9461-4162-b2b9-581ba2266658" />

**Comment by Mortemtail** [comment]
Well, actually I still have some issues with the Windows Settings menu, it doesn’t want to close, like all the other app i mentioned before, it's like the issue came back frome nowhere few times after the downloading of the update
